---
abstract: 'Reorder columns of TSV file by template'
author:
  - 'Ian Sealy <cpan@iansealy.com>'
build_requires:
  Capture::Tiny: '0'
  ExtUtils::MakeMaker: '0'
  File::Slurper: '0'
  File::Spec: '0'
  Test::Exception: '0'
  Test::More: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Reorder-TSV
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  App::Reorder::TSV:
    file: lib/App/Reorder/TSV.pm
    version: v0.1.0
requires:
  Carp: '0'
  Exporter: '0'
  Getopt::Long: '0'
  IO::Uncompress::Gunzip: '0'
  Pod::Usage: '0'
  autodie: '0'
  strictures: '2'
version: 0.1.0
x_Dist_Zilla:
  perl:
    version: '5.028003'
  plugins:
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.015'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.015'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Default/SingleEncoding'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.015'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.015'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.015'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: '4.015'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: '4.015'
      name: PodWeaver
      version: '4.008'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: Test::Perl::Critic
      version: '3.001'
    -
      class: Dist::Zilla::Plugin::PerlTidy
      name: PerlTidy
      version: '0.21'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: OurPkgVersion
      version: '0.21'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: CopyFilesFromBuild
      version: '0.170880'
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match:
            - LICENSE|Makefile.PL|META.yml|META.json
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory: []
          root: .
      name: '@Filter/GatherDir'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Filter/Test::ReportPrereqs'
      version: '0.028'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: 0
          filename: xt/author/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: 0
          phase: develop
          script_finder:
            - ':PerlExecFiles'
          skips: []
          switch: []
      name: '@Filter/Test::Compile'
      version: '2.058'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Filter/MakeMaker'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Filter/RunExtraTests'
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Filter/MetaNoIndex'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Filter/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '6.015'
          include_underscores: 0
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002004'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000037'
          version: '0.006'
      name: '@Filter/MetaProvides::Package'
      version: '2.004003'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: ExecDir
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::Encoding
      name: Encoding
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Filter/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '6.015'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '6.015'
x_generated_by_perl: v5.28.3
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: GPL-3.0-only
